# 데이터 분석 프로세스


##### *데이터 로딩 
##### *데이터 세트 분리 : 데이터를 학습데이터와 테스트데이터로 분리
##### *모델 학습 : 학습 데이터르 기반으로 ML 알고리즘을 적용해서 모델을 학습시킴
##### *예측 수행 : 학습된 모델을 이용해서 분류된 테스트 데이터를 예측
##### *평가 : 예측된 결과값과 테스트데이터의 실제 결과값(label)을 비교해서 ML 모델 성능을 평가

##### 학습 : fit,  예측 : predict

# Iris(붓꽃) 데이터
## 품종 예측하기

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
# 붓꽃 데이터를 로딩

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
'''
머신러닝 - 데이터셋 용어

feature(특성) : 예측을 수행하는 데 사용되는 입력 변수
data : 피처의 데이터 세트
target : 분류를 통해서 얻어내야할 정답(label값) 라벨0번의 품종이 몇번인지...
target_name : 개별 레이블 이름
feature_name : 개별 피처의 이름
DESCR : 데이터 세트에 대한 설명과 각 피처에 대한 설명
'''

In [5]:
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
# 붓꽃 데이터 세트를 자세히 보기 위해 데이터프레임으로 확인
# 모든 데이터가 보기 좋게 가공되어 있지는 않음.

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

# label 0 : setosa
# label 1 : versicolor
# label 2 : virginica

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [10]:
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
145      2  
146      2  
147      2  
148      2  
149      2

In [11]:
# 학습용 데이터와, 테스트용 데이터 분리
# 중간 중간 확인할 수 있어야함 -> 평가 데이터

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)      

# 전체 데이터세트 중 20%를 테스트데이터로 사용하겠다는 뜻
# 나머지 80%는 학습 데이터

# 독립변수는 대문자로 적고, 종속변수는 소문자로

In [12]:
# 결정 트리 모델(DecisionTreeClassifier) 결정트리분류모델
# 분류 목적의 모델 객체는 clf를 붙여 네이밍

df_clf = DecisionTreeClassifier(random_state=11)
df_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [15]:
# 학습이 완료된 모델을 통해 테스트 데이터로 예측 수행
# 위의 코드로 인해 df_clf 객체는 학습이 된 상태.
# 학습시킨 다음 어떤 답을 내놓을지 시험을 보는 것.

pred = df_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [16]:
# 위 예측된 결과를 바탕으로 모델의 품종 예측 성능을 평가

from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도 : 0.9333


# ***데이터 세트 살펴보기***

In [ ]:
# 한 파일 내에서 학습된 모델을 다시 사용하면 문제가 생길 수도 있으니 새로 불러오는 것을 권장

from sklearn.datasets import load_iris

In [17]:
iris_data = load_iris()
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
print(type(iris_data))  # ==> Bunch 클래스는 파이썬 딕셔너리와 유사. 

keys = iris_data.keys()
keys

<class 'sklearn.utils.Bunch'>


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
iris_data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [20]:
print('feature_names type', type(iris_data.feature_names))
print('freatur_names length', len(iris_data.feature_names))
print(iris_data.feature_names)

feature_names type <class 'list'>
freatur_names length 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [22]:
print('target_names type : ', type(iris_data.target_names))
print('target_names len : ', len(iris_data.target_names))
print(iris_data.target_names)

target_names type :  <class 'numpy.ndarray'>
target_names len :  3
['setosa' 'versicolor' 'virginica']


 # ***모델 학습 시 유의사항***
 #### 학습 데이터와 테스트 데이터를 나누지 않으면 어떻게 되는가?

In [23]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [24]:
# 학습데이터 세트로만 학습하고 예측하기

In [25]:
iris = load_iris()
clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
clf.fit(train_data, train_label)

DecisionTreeClassifier()

In [26]:
# 예측 - 정확도 평가
pred = clf.predict(train_data)
print('예측 정확도 : ', accuracy_score(train_label, pred))

예측 정확도 :  1.0


# ***과적합 개선 - 교차검증***

In [ ]:
# 내부 데이터를 나눠서 가르치고 예측하고 평가 --> 교차검증.
# 한 번에 다 가르치면 과적합이 발생 (overfitting)

# K 폴드 (보편적으로 사용하는 교차 검증 기법)

'''
k폴드를 사용해서, 5번 나눠서 학습시킨다고 할 때,
1회차에는 20%의 테스트 데이터, 80%의 학습 데이터
2회차에는 40%의 테스트 데이터, 60%의 학습 데이터
3회차에는 60%의 테스트 데이터, 40%의 학습 데이터
4회차에는 80%의 테스트 데이터, 20%의 학습 데이터
5회차에는 100%의 테스트 데이터
'''

In [37]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np

In [38]:
iris = load_iris()
features = iris.data
clf = DecisionTreeClassifier(random_state=121)
label = iris.target

# 5개의 폴드 세트, 폴드 세트별 정확도를 담을 리스트 객체 선언 
KFold = KFold(n_splits=5)
cv_accuracy = []

In [39]:
# 데이터 세트의 크기 - 튜플로 리턴(행, 열)
features.shape

(150, 4)

In [44]:
n_iter = 0

for train_index, test_index, in KFold.split(feature):
    # 반환된 인덱스 번호를 이용하여 학습용, 테스트용 데이터를 분리
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    clf.fit(X_train, y_train)
    pred = clf.predict(X_test)
    n_iter += 1
    # 반복할 때마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    # 교차 검증 정확도, 학습 데이터 크기, 검증 데이터 크기, 검증 세트 인덱스
    train_data_size = X_train.shape[0]
    test_data_size = X_test.shape[0]
    # 각 폴드별 결과 확인
    print('\n #{0} 교차검증정확도 : {1} \n 학습데이터 크기 : {2} \n 검증데이터 크기 {3}'
          .format(n_iter, accuracy, train_data_size, test_data_size))
    print('#{0} 검증세트 인덱스 {1}'.format(n_iter, test_index))
    # 각 폴드별 정확도를 리스트에 담기
    cv_accuracy.append(accuracy)


 #1 교차검증정확도 : 1.0 
 학습데이터 크기 : 120 
 검증데이터 크기 30
#1 검증세트 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 #2 교차검증정확도 : 1.0 
 학습데이터 크기 : 120 
 검증데이터 크기 30
#2 검증세트 인덱스 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 #3 교차검증정확도 : 0.9 
 학습데이터 크기 : 120 
 검증데이터 크기 30
#3 검증세트 인덱스 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 #4 교차검증정확도 : 0.9333 
 학습데이터 크기 : 120 
 검증데이터 크기 30
#4 검증세트 인덱스 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 #5 교차검증정확도 : 0.7333 
 학습데이터 크기 : 120 
 검증데이터 크기 30
#5 검증세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [45]:
# 개별 폴드별 정확도를 합하여 평균 정확도 계산
print('평균 검증 정확도 : ', np.mean(cv_accuracy))

평균 검증 정확도 :  0.91332


In [ ]:
# KFold를 사용하여 과적합을 예방할 수는 있으나,
# 학습과정이 점점 길어지기 때문에,
# 가장 좋은 것은 학습설계단계부터 학습 데이터와, 테스트 데이터를 잘 구분하는 것

In [ ]:
# 오늘자 머신러닝 해 본 Iris 데이터는
# 피처 사이즈 150, 테스트 데이터 30개
# 이 모델의 실성능을 평가하기는 어렵다.
# 실용성이 있어야하기 때문.