In [1]:
'''
# numpy : 고성능 과학(수치) 계산을 위한 데이터분석(수치분석) 패키지
#       : 벡터 산술연산
#    : 다차원 배열 ( ndarray)
#    : 표준 수학 함수
#    : 선형대수, 난수
'''
import numpy as np
x = np.array([18, 5, 10, 2, 3, 11, -3, -5, -30, 15, 6, 78, -13, 9, 5, 7, 8, 3, 80, -4])
x

array([ 18,   5,  10,   2,   3,  11,  -3,  -5, -30,  15,   6,  78, -13,
         9,   5,   7,   8,   3,  80,  -4])

In [ ]:
len(x)

In [3]:
# 평균(average, mean)
np.mean(x)

25.073641538476217

In [ ]:
# 분산(variance) : 데이터와 샘플 평균 간의 거리의 제곱의 평균
#                : 이 값이 작으면 데이터가 모여 있는 것
#                : 이 값이 크면 데이터가 흩어져 있는 것
np.var(x)

In [ ]:
# 표준편차 (standard deviation) : 분산의 제곱근 값
np.std(x)

In [ ]:
# 최대값 ( maximum)
np.max(x)


In [ ]:
# 최소값(minimum)
np.min(x)

In [ ]:
# 중앙값 (medium)
# : 데이터를 크기대로 정렬했을 때 가운데에 있는 수
# : 데이터 갯수가 짝수인 경우 중앙의 두 수 평균을 사용
np.median(x)

In [5]:
# 사분위수(quartile) 
# : 데이터를 크기대로 정렬했을 때, 
# : 1/4, 2/4, 3/4 위치에 있는 수를 말한다
# : 1사분위수, 2사분위수, 3사분위수라고 함
# : 데이터가 100개 있다면 25번 째가 1사분위수,
# : 2사분위수는 중앙값과 같음
# : 위치를 1/100 단위로 나누는 백분위수(percentile)을 사용하기도 함

print(np.percentile(x, 0))     # = min() 와 같음
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))
print(np.percentile(x, 100))   # = max() 와 같음 

-30.0
0.75
5.5
10.25
80.0


In [ ]:


np.product(x)

In [ ]:
# numpy 배열
'''
같은 종류의 데이터를 담는 자료형 (동일한 타입의 값)
- rank : 배열 차원 (ndim)
- shape : 각 차원의 크기를 튜플로 리턴 (행, 열)
- dtype : 배열에 저장된 자료를 알려주는 객체
'''

In [6]:
a = np.array([1,2,3])
b = [1,2,3]
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# numpy 배열 객체 
- array() : 배열 생성
- arange() : 배열 생성 시 지정 값까지 자동 생성
- reshape() : 배열 모양 변경
- zeros() : 0이 들어있는 배열 생성
- ones() : 1이 들어있는 배열 생성
- full() : 모든 값이 특정 상수인 배열을 생성
- eye() : 단위 행렬 생성

In [8]:
np.ndim(a)


1

In [7]:
# 2차원 배열 생성
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(b.ndim, b.shape, b.dtype)

2 (2, 3) int64


In [10]:
b.itemsize       # itemsize : 각 배열 요소가 메모리 상에서 차지하고 있는 크기 - 보통 int 자료형은 4byte

8

In [12]:
# arange()
arr = np.arange(12)   # 0부터 시작하는 numpy array 객체를 생성
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
# 배열 형태 변환 : reshape()
# 3행 4열로 만들기

arr = np.arange(12).reshape(3, 4); arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr.reshape(-1)   # 입력항목으로 -1을 넣으면 원래대로 돌려줌


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# zeros()    # 입력항목으로 튜플이 들어와야함.
# : 다차원 배열을 만드는 값을 튜플로 받아들여 0 으로 채워진 배열을 반환
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# ones()    
# : zeros()와 마찬가지로 동작, 1로 채워진 다차원 배열 반환
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# full()              # (x, y)  
# x = 다차원 배열을 생성할 튜플값, y = 채울 값
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [18]:
# 단위행렬
# eye()  : 1행1열, 2행2열, 3행3열 계단식으로 1이 채워지고, 나머지는 0을 채우는 배열을 생성
np.eye(3)           

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# ndarray - 임의의 데이터를 만들어서 모델에게 테스트하는 용도로 주로 사용
np.random.random((2, 2))


array([[0.72344419, 0.6085922 ],
       [0.21301457, 0.44427031]])

In [21]:
# 슬라이싱 : 파이선 리스트와 똑같이 numpy 객체도 슬라이싱 가능
#          : 슬라이싱 된 배열은 원본 배열과 같은 데이터를 참조함
#          : 그러므로 슬라이싱 된 배열을 수정하면 원본 배열도 수정 된다.
#          : ==> 슬라이싱 결과는 언제나 원본 배열의 부분을 보여주는 것뿐, 새로운 객체가 아님

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
# (1, 2, 5, 6) 을 가져오고 싶음

b = a[:2, :2]; b

array([[1, 2],
       [5, 6]])

In [26]:
# (2, 3, 6, 7) 가져오기

c = a[:2, 1:3]; c

array([[2, 3],
       [6, 7]])

In [27]:
# 인덱싱
# numpy 배열 인덱싱은 팬시 인덱싱(fancy indexing)이라고 함
# 배열 인덱싱의 유용한 기능 중 하나는, 행렬의 각 행에서 하나의 요소를 선택, 수정하는 기능
# 정수 배열 인덱싱을 하는 경우 원본과 다른 배열 객체를 만들 수 있음

print(b)
print('='*40)
b[0, 0]


[[1 2]
 [5 6]]


1

In [30]:
b[0, 0] = 100; b
print(a)

# numpy 배열객체 b의 값을 수정 후 , 원본 배열객체 a를 프린트 해보면, 값이 변한 것이 반영되었다.

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
# (5, 6, 7, 8)을 가져오기 => 2번째 행을 추출
# a[x,y] 형식의 y 값을 인덱싱으로 입력하면 행 형태로 가져옴
d = a[1, :]; d

array([5, 6, 7, 8])

In [33]:
print(d.ndim, d.shape)

1 (4,)


In [43]:
# (2, 6, 10)을 가져와서 변수 e에 담기  ==> 2번째 열을 추출
# a[x,y] 형식의 y 값을 슬라이싱으로 입력하면 열 형태로 가져옴
e = a[:3, 1:2]; e

array([[ 2],
       [ 6],
       [10]])

In [40]:
print(e.ndim, e.shape)

1 (3,)


In [44]:
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# (1, 4, 5) 추출
# 리스트를 이용하여 원하는 행과 열을 각각 짝지어서 추출할 수 있음

f = a[[0, 1, 2], [0, 1, 0]]; f

array([1, 4, 5])

In [47]:
f.shape

(3,)

In [48]:
# 정수 인덱싱
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
idx = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 8]); idx

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 8])

In [53]:
a[idx]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 9])

In [61]:
# 부울 인덱싱
a = np.array([[1, 2], [3, 4], [5, 6]])
a 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
# (1, 3, 5) 추출 ==> 열 형태로

b = a[:, [True, False]]; b

array([[1],
       [3],
       [5]])

In [64]:
b.shape

(3, 1)

In [65]:
# 배열 연산
# 배열의 각 요소별로 동작 
# 수학 함수, 연산자, numpy 함수를 통해 배열 연산이 가능

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [67]:
print(x)
print('=======================')
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [68]:
x + y

array([[ 6,  8],
       [10, 12]])

In [69]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [70]:
x - y

array([[-4, -4],
       [-4, -4]])

In [71]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [72]:
x * y

array([[ 5, 12],
       [21, 32]])

In [73]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [74]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [75]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [77]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [78]:
# numpy 객체 배열 연산에 조건식 사용 가능

x == 2          # 배열 중에 '2'의 유무를 Boolean으로 반환

array([[False,  True],
       [False, False]])

In [79]:
y > 6

array([[False, False],
       [ True,  True]])

In [80]:
# 논리 연산도 가능

(x > 3) & (y > 6)

array([[False, False],
       [False,  True]])

In [ ]:
# 브로드캐스팅 (broadcasting)
# : 모양이 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능하도록 배열을 자동적으로 변환하는 것

# 원칙             ====>  특정 조건
# 1 2 + 10 10             1 2 + 10
# 3 4 + 10 10             3 4 

# 브로드캐스팅이 일어날 수 있는 조건
# - 차원 크기가 스칼라라면 가능 
# (*스칼라 : 방향의 구별 없이 수치만 존재하는 1차원의 물리량)
# (*벡터, 텐서 등은 방향과 크기가 있는 물리량.)
# - 차원 크기가 스칼라가 아니라면 차원의 짝이 맞은 조건 (축의 길이가 같을 때)

In [82]:
a = np.array([[1, 2], [3, 4]])
b = 10

print(a+b)

# b는 10을 갖는 객체이지만 배열a와 연산 결과, 
# 2열2행의 10이 채워진 배열로 연산이 된다.

[[11 12]
 [13 14]]


In [90]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

# print(a + b)

# 같은 차원의 배열이지만 서로 짝이 맞지 않아서 연산이 불가능

In [84]:
x = np.arange(3)
y = 5

x + y

array([5, 6, 7])

In [86]:
x = np.ones((3, 3))
y = np.arange(3)

x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [89]:
x = np.arange(3).reshape(3, 1)
x

x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])